# Generated by Django 5.0.7 on 2024-08-24 15:39

import account.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='آدرس ایمیل')),
                ('fullname', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام کامل')),
                ('phone_number', models.CharField(max_length=12, unique=True, validators=[account.validators.validate_phone_number], verbose_name='شماره همراه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربرها',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=127, verbose_name='تحویل گیرنده')),
                ('phone', models.CharField(max_length=11, validators=[account.validators.validate_phone_number], verbose_name='شماره تماس')),
                ('address', models.TextField(verbose_name='نشانی کامل')),
                ('postal_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('is_active', models.BooleanField(default=True, verbose_name='آدرس فعال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس ها',
                'ordering': ['-is_active'],
            },
        ),
    ]
