# Generated by Django 5.0.7 on 2024-08-25 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_product_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_info', models.TextField(blank=True, null=True, verbose_name='اطلاعات گیرنده')),
                ('total_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='مجموع کل اصلی')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت پرداخت')),
                ('ref_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره پیگیری')),
                ('post_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='کد پیگیری پستی')),
                ('status', models.CharField(blank=True, choices=[('در انتظار تایید', 'در انتظار تایید'), ('در حال آماده سازی', 'در حال آماده سازی'), ('تحویل پست داده شده', 'تحویل پست داده شده'), ('دریافت شده', 'دریافت شده')], max_length=20, null=True, verbose_name='وضعیت سفارش')),
                ('post_price', models.PositiveIntegerField(default=0, verbose_name='هزینۀ پست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش ها',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='تعداد')),
                ('total_price', models.PositiveIntegerField(verbose_name='قیمت اصلی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='کاربر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'محصول خریداری شده',
                'verbose_name_plural': 'محصولات خریداری شده',
            },
        ),
    ]
