# Generated by Django 5.0.7 on 2024-08-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='مجموع کل اصلی'),
        ),
    ]
